# custom_components/dynamic_energy_calculator/entity.py

from __future__ import annotations

from homeassistant.core import HomeAssistant
from homeassistant.config_entries import ConfigEntry
from homeassistant.helpers.entity import Entity
from homeassistant.helpers.device_registry import DeviceInfo

from .const import DOMAIN

class DynamicEnergyEntity(Entity):
    """Base entity for Dynamic Energy Calculator."""

    def __init__(
        self,
        hass: HomeAssistant,
        entry: ConfigEntry,
        key: str,
        name: str,
        device_id: str,
        device_name: str,
        device_model: str,
    ) -> None:
        """Initialize common attributes for all entities."""
        self.hass = hass
        self._entry = entry

        # Friendly names are provided by the integration (no autogenerated suffixes)
        self._attr_has_entity_name = True
        # The display name in the UI
        self._attr_name = name
        # Unique per integration entry & key
        self._attr_unique_id = f"{entry.entry_id}_{key}"
        # Group under a single device in Devices & Services
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, device_id)},
            name=device_name,
            manufacturer="Dynamic Energy Calculator",
            model=device_model,
        )
        # We push updates via events, never poll
        self._attr_should_poll = False
